[project]
name = "btc-timeseries-ml"
version = "0.1.0"
description = "Bitcoin timeseries machine learning."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "statsmodels",
    "scikit-learn",
    "jupyterlab",
    "statsmodels", 
    "joblib"
    
]

[tool.pytest.ini_options]
testpaths = ["tests"]
